export const ROUTES = {
  home:      '/',
  about:     '/about',
  products:  '/products',
  ingredients: '/ingredients',
  product:   (id: string) => `/products/${id}`,
  blog:      '/blog',
  events:    '/events',
  locations: '/locations',
  contact:   '/contact',

  login:     '/login',

  admin: {
    root:        '/admin',
    dashboard:   '/admin/dashboard',
    products:    '/admin/products',
    ingredients: '/admin/ingredients',
    reviews:     '/admin/reviews',
    blog:        '/admin/blog',
    locations:   '/admin/locations',
    subscribers: '/admin/subscribers',
    messages:    '/admin/messages',
    events:      '/admin/events',
    stock:       '/admin/stock',
    finance:     '/admin/finance',
    reports:     '/admin/reports',
    settings:    '/admin/settings',
    data:        '/admin/data',
  },
} as const;
