export const ROUTES = {
home:      '/',
about:     '/about',
products:  '/products',
ingredients: '/ingredients',
product:   (id: string) => `/products/${id}`,
recipes:   '/recipes',
blog:      '/blog',
events:    '/events',
locations: '/locations',
contact:   '/contact',
cart:      '/cart',
checkout:  '/checkout',

login:     '/login',

  admin: {
    root:        '/admin',
    dashboard:   '/admin/dashboard',
    products:    '/admin/products',
    productSettings: '/admin/product-settings',
    ingredients: '/admin/ingredients',
    blogSettings: '/admin/blog-settings',
    reviews:     '/admin/reviews',
    blog:        '/admin/blog',
    eventSettings: '/admin/event-settings',
    locations:   '/admin/locations',
    locationSettings: '/admin/location-settings',
    subscribers: '/admin/subscribers',
    messages:    '/admin/messages',
    events:      '/admin/events',
    stock:       '/admin/stock',
    finance:     '/admin/finance',
    reports:     '/admin/reports',
    settings:    '/admin/settings',
    data:        '/admin/data',
  },
} as const;
