import type { Product }    from '@/features/products/types/product.types';
import type { Review }     from '@/features/reviews/types/review.types';
import type { BlogPost }   from '@/features/blog/types/blog.types';
import type { Location }   from '@/features/locations/types/location.types';
import type { Subscriber } from '@/features/newsletter/types/subscriber.types';
import type { Message }    from '@/features/contact/types/message.types';
import type { Activity }   from '@/features/dashboard/types/dashboard.types';
import type { Settings }   from '@/features/auth/types/auth.types';
import type { Event }         from '@/features/events/types/event.types';
import type { StockMovement } from '@/features/stock/types/stock.types';
import type { Transaction }   from '@/features/finance/types/finance.types';
import type { Ingredient } from '@/features/ingredients/types/ingredient.types';
import type { Recipe } from '@/features/recipes/types/recipe.types';

const SB   = 'https://gflkfwalfaeeknauxyig.supabase.co/storage/v1/object/public/images';
const SUPA = 'https://gflkfwalfaeeknauxyig.supabase.co/storage/v1/object/public';

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Soleil du Sahel',
    category: 'Jus',
    price: 9.00,
    formats: ['355ml', '1L'],
    desc: "L'hibiscus rouge de Casamance rencontre le gingembre piquant et une touche de tamarin \u2014 chaque gorgée évoque les marchés animés du Sénégal.",
    available: true,
    tag: 'Pressé à froid',
    img: `${SB}/products/soleil-du-sahel.jpg`,
    color: '#c44536',
  },
  {
    id: 'p2',
    name: 'Rivière Verte',
    category: 'Jus',
    price: 10.00,
    formats: ['355ml', '1L'],
    desc: "Concombre du Québec, épinard, pomme Cortland et menthe fraîche \u2014 une harmonie alpine légère, vive et profondément vivifiante.",
    available: true,
    tag: '100% Naturel',
    img: `${SB}/products/riviere-verte.jpg`,
    color: '#2a6a4f',
  },
  {
    id: 'p3',
    name: 'Fleur de Baobab',
    category: 'Jus',
    price: 12.00,
    formats: ['355ml'],
    desc: "La pulpe crèmeuse du baobab sacré mariée à la mangue Ataulfo et au curcuma doré \u2014 exotique, enveloppante et riche en vitamine C.",
    available: true,
    tag: 'Boost Immunité',
    img: `${SB}/products/fleur-de-baobab.jpg`,
    color: '#d4763b',
  },
  {
    id: 'p4',
    name: 'Nuit de Kinshasa',
    category: 'Jus',
    price: 11.00,
    formats: ['355ml', '1L'],
    desc: "Betterave pourpre, cassis sauvage et hibiscus \u2014 intense, mystérieux et envoûtant, riché en antioxydants naturels pour la récupération.",
    available: true,
    tag: 'Sans sucre ajouté',
    img: `${SB}/products/nuit-de-kinshasa.jpg`,
    color: '#6b2d8b',
  },
  {
    id: 'p5',
    name: 'Aurore Boréale',
    category: 'Jus',
    price: 9.00,
    formats: ['355ml', '1L'],
    desc: "Carotte bio, orange sanguine et curcuma \u2014 une palette orangée et rose qui rappelle le ciel boréal à l'aube, riche en bêta-carotène.",
    available: true,
    tag: 'Bio',
    img: `${SB}/products/aurore-boreale.jpg`,
    color: '#e8732a',
  },
  {
    id: 'p6',
    name: 'Tam-Tam Tropical',
    category: 'Jus',
    price: 10.00,
    formats: ['355ml', '1L'],
    desc: "Ananas frais pressé à froid, noix de coco, citron vert et vanille de Madagascar \u2014 une symphonie sucrée-acidulée qui transporte sur une plage africaine.",
    available: true,
    tag: '100% Naturel',
    img: `${SB}/products/tam-tam-tropical.jpg`,
    color: '#f4a261',
  },
  {
    id: 'p7',
    name: 'Sage de la Savane',
    category: 'Jus',
    price: 13.00,
    formats: ['355ml'],
    desc: "La moringa \u2014 l\u2019arbre miracle à 92 nutriments \u2014 réveillée par le citron Meyer, le céleri et la pomme verte. Nutrition à l\u2019état pur.",
    available: true,
    tag: 'Bio',
    img: `${SB}/products/sage-de-la-savane.jpg`,
    color: '#1a5e3a',
  },
  {
    id: 'p8',
    name: 'Feu Gnamakoudji',
    category: 'Jus',
    price: 8.00,
    formats: ['60ml', '355ml'],
    desc: "L\u2019eau de gingembre emblématique de Côte d\u2019Ivoire \u2014 gingembre frais bio, cardamome et citron concentrés en un shot intense qui réveille et purifie.",
    available: true,
    tag: 'Boost Immunité',
    img: `${SB}/products/feu-gnamakoudji.jpg`,
    color: '#bc6c25',
  },
  {
    id: 'p9',
    name: 'Calebasse Dorée',
    category: 'Jus',
    price: 12.00,
    formats: ['355ml', '1L'],
    desc: "Papaye fraîche, ananas, curcuma et mangue \u2014 d\u2019une douceur royale et riche en enzymes digestives naturelles, le soin du matin par excellence.",
    available: true,
    tag: 'Sans sucre ajouté',
    img: `${SB}/products/calebasse-doree.jpg`,
    color: '#d4a853',
  },
  {
    id: 'p10',
    name: 'Neige Rouge',
    category: 'Jus',
    price: 11.00,
    formats: ['355ml', '1L'],
    desc: "Canneberges sauvages du Québec, fraises des champs et grenade africaine \u2014 une fusion unique née du froid et de l\u2019amour des deux cultures de Ben\u2019s.",
    available: true,
    tag: 'Pressé à froid',
    img: `${SB}/products/neige-rouge.jpg`,
    color: '#8b1a1a',
  },
  /* ── TISANES ── */
  {
    id: 't1',
    name: 'Tisane Hibiscus Rouge',
    category: 'Tisanes',
    price: 9.50,
    formats: ['50g', '100g'],
    desc: "Un rituel du soir hérité de nos grand-mères. Fleurs d'hibiscus séchées à la main, infusées lentement pour libérer leur couleur rouge cardinal et leurs antioxydants naturels.",
    available: true,
    tag: '100% Naturel',
    img: `${SUPA}/tisanes/tisane-hibiscus.jpg`,
    color: '#c44536',
  },
  {
    id: 't2',
    name: 'Tisane Gingembre & Citron',
    category: 'Tisanes',
    price: 9.50,
    formats: ['50g', '100g'],
    desc: "Le mariage parfait du gingembre piquant et du citron vif — une tisane tonifiante qui réchauffe de l'intérieur et soutient le système immunitaire à chaque tasse.",
    available: true,
    tag: 'Boost Immunité',
    img: `${SUPA}/tisanes/tisane-gingembre.jpg`,
    color: '#bc6c25',
  },
  {
    id: 't3',
    name: 'Infusion Menthe Sauvage',
    category: 'Tisanes',
    price: 8.50,
    formats: ['50g', '100g'],
    desc: "Menthe fraîche séchée naturellement, récoltée au Québec. Une infusion légère, fraîche et apaisante — le rituel parfait après le repas ou avant le sommeil.",
    available: true,
    tag: '100% Naturel',
    img: `${SUPA}/tisanes/tisane-menthe.jpg`,
    color: '#2a6a4f',
  },
  /* ── SIROPS ── */
  {
    id: 's1',
    name: "Sirop d'Hibiscus",
    category: 'Sirops',
    price: 14.00,
    formats: ['250ml', '500ml'],
    desc: "L'essence pure de la fleur d'hibiscus concentrée en quelques gouttes. Un sirop vivant, intense et acidulé qui transforme votre quotidien en cérémonie.",
    available: true,
    tag: 'Sans sucre ajouté',
    img: `${SUPA}/sirops/sirop-hibiscus.jpg`,
    color: '#c44536',
  },
  {
    id: 's2',
    name: 'Sirop de Gingembre',
    category: 'Sirops',
    price: 14.00,
    formats: ['250ml', '500ml'],
    desc: "Gingembre frais pressé et concentré — piquant, chaleureux, enveloppant. Idéal dans l'eau pétillante, les cocktails ou les marinades pour une touche africaine.",
    available: true,
    tag: 'Pressé à froid',
    img: `${SUPA}/sirops/sirop-gingembre.jpg`,
    color: '#bc6c25',
  },
  {
    id: 's3',
    name: "Sirop d'Ananas",
    category: 'Sirops',
    price: 12.00,
    formats: ['250ml', '500ml'],
    desc: "La douceur tropicale de l'ananas en format concentré. Riche en bromélaïne naturelle, ce sirop apporte une fraîcheur estivale à toutes vos boissons et desserts.",
    available: true,
    tag: '100% Naturel',
    img: `${SUPA}/sirops/sirop-ananas.jpg`,
    color: '#f4a261',
  },
  /* ── POUDRES (vrais produits du site lesjusnaturelsbens.com) ── */
  {
    id: 'poudre1',
    name: 'Poudre de Gingembre',
    category: 'Poudres',
    price: 11.00,
    formats: ['100g', '250g'],
    desc: "Un concentré d'énergie ancestrale — gingembre sauvage séché et moulu, au goût piquant et légèrement sucré. Aide la digestion, anti-inflammatoire naturel, boost immunitaire.",
    available: true,
    tag: 'Bio',
    img: `${SUPA}/poudres/poudre-gingembre.jpg`,
    color: '#bc6c25',
  },
  {
    id: 'poudre2',
    name: "Poudre d'Hibiscus Rouge",
    category: 'Poudres',
    price: 12.00,
    formats: ['100g', '250g'],
    desc: "Fleurs d'hibiscus séchées et réduites en poudre fine — acidulée, riche en antioxydants et vitamine C. À infuser, à saupoudrer sur vos yaourts ou à ajouter aux smoothies.",
    available: true,
    tag: '100% Naturel',
    img: `${SUPA}/poudres/poudre-hibiscus.jpg`,
    color: '#c44536',
  },
  {
    id: 'poudre3',
    name: "Poudre d'Hibiscus & Gingembre",
    category: 'Poudres',
    price: 13.00,
    formats: ['100g', '250g'],
    desc: "Le mariage parfait de la fraîcheur acidulée de l'hibiscus et de la chaleur piquante du gingembre. Soutien digestif, anti-inflammatoire et boost circulatoire en une seule poudre.",
    available: true,
    tag: 'Boost Immunité',
    img: `${SUPA}/poudres/poudre-curcuma.jpg`,
    color: '#d4a853',
  },
];

export const SEED_REVIEWS: Review[] = [
  { id: 'r1', name: 'Clarice Turner',     text: "J'adore absolument ces jus ! Le jus d'hibiscus est mon préféré — il est rafraîchissant, délicieux et donne une vraie sensation de bien-être.", rating: 5, approved: true,  date: '2025-11-12' },
  { id: 'r2', name: 'Brian Moten',        text: "Le jus d'ananas de Les Jus Naturels Ben's a le goût du fruit frais. J'adore qu'il soit sans sucre ajouté ni conservateurs.", rating: 5, approved: true,  date: '2025-12-03' },
  { id: 'r3', name: 'Jeanne Tremblay',    text: "Je bois 1 litre de tisane d'hibiscus à tous les jours. J'adore le goût et sa couleur rouge. Un vrai rituel bien-être quotidien !", rating: 5, approved: true,  date: '2026-01-18' },
  { id: 'r4', name: 'Ibrahim Konaté',     text: "Le Feu Gnamakoudji, c'est exactement comme chez ma mère à Abidjan. Ben's a réussi quelque chose de rare : l'authenticité en bouteille.", rating: 5, approved: false, date: '2026-02-18' },
];

export const SEED_BLOGS: BlogPost[] = [
  {
    id: 'b1',
    title: 'Le Bissap : bien plus qu\u2019une boisson, un trésor culturel d\u2019Afrique de l\u2019Ouest',
    category: 'Héritage & Culture',
    content: "Connu sous mille noms \u2014 zobo au Nigeria, sobolo au Ghana, karkadé en Égypte \u2014 le bissap est l\u2019un des jus les plus anciens et les plus riches du continent africain. Chez Les Jus Naturels Ben\u2019s, nous le pressons à froid pour préserver chacun de ses antioxydants naturels, sa couleur rouge cardinal et son goût floral incomparable.\n\nChaque fleur d\u2019hibiscus que nous utilisons provient de Casamance, au Sénégal, sélectionnée par des producteurs partenaires avec qui nous travaillons directement depuis la création de l\u2019atelier. C\u2019est cette traçabilité \u2014 du champ à la bouteille \u2014 qui donne au bissap Ben\u2019s son caractère unique.\n\nRiche en vitamine C, en anthocyanines et en polyphenôls, le bissap est reconnu par la recherche scientifique pour ses propriétés cardiovasculaires, son action sur la pression artérielle et sa capacité à neutraliser les radicaux libres. Mais au-delà de la science, c\u2019est un lien vivant avec l\u2019Afrique de l\u2019Ouest \u2014 une boisson de fête, de partage et de bienvenue.",
    published: true,
    date: '2026-01-20',
    img: `${SB}/blog/bissap-culture.jpg`,
    tags: ['bissap', 'hibiscus', 'Afrique', 'tradition', 'antioxydants'],
    contentType: 'article',
  },
  {
    id: 'b2',
    title: 'Pourquoi la pression à froid change tout : la science derrière chaque bouteille',
    category: 'Science & Nutrition',
    content: "La pression à froid n\u2019est pas qu\u2019une tendance \u2014 c\u2019est une révolution dans la façon dont nous extrayons la vie des fruits et légumes. Sans chaleur, sans oxydation, sans compromis : les enzymes, vitamines et minéraux restent intacts du pressoir à vos lèvres.\n\nLa pasteurisation thermique, utilisée par la grande majorité des jus commerciaux, détruit jusqu\u2019à 70% des vitamines thermosensibles (vitamine C, folates, B6) et dénature la totalité des enzymes digestives. Le goût, la couleur et la valeur nutritionnelle en sont profondément affectés.\n\nNotreresse hydraulique à froid travaille à une pression de 6 000 bar sans dépasser 4\u00b0C. Le résultat : un jus vivant, dense en nutriments, avec une durée de conservation naturelle de 3 à 5 jours au réfrigérateur. Pas de conservateur. Pas de concentré. Juste la nature, aussi proche de l\u2019arbre que possible.",
    published: true,
    date: '2026-02-08',
    img: `${SB}/blog/cold-press.jpg`,
    tags: ['pression à froid', 'cold pressed', 'nutrition', 'enzymes', 'santé'],
    contentType: 'article',
  },
  {
    id: 'b3',
    title: 'De Jean-Talon à Dakar : comment Ben\u2019s source ses ingrédients avec intention',
    category: 'Notre Histoire',
    content: "Chaque mardi matin, vous nous trouverez au marché Jean-Talon à l\u2019aube, en train de sélectionner à la main les épinards du Québec, les carottes biologiques et les herbes fraîches de nos producteurs partenaires. Et chaque saison, nous travaillons avec des importateurs spécialisés pour ramener fidèlement le baobab, la moringa et le bissap directement d\u2019Afrique de l\u2019Ouest.\n\nCette double fidélité \u2014 à la terre québécoise et aux racines africaines \u2014 n\u2019est pas un argument marketing. C\u2019est l\u2019histoire personnelle de Ben\u2019s, né à Dakar et installé à Montréal depuis vingt ans.\n\nNos fournisseurs québécois sont visités plusieurs fois par saison. Nos partenaires africains sont choisis pour leur engagement envers une agriculture sans pesticides. Et pour chaque ingrédient exotique, nous vérifions les conditions de travail des récoltants. Parce qu\u2019un jus éthique commence bien avant le pressoir.",
    published: true,
    date: '2026-03-01',
    img: `${SB}/blog/marche-jean-talon.jpg`,
    tags: ['local', 'Québec', 'approvisionnement', 'marché Jean-Talon', 'artisanal', 'Afrique'],
    contentType: 'article',
  },
];

export const SEED_LOCATIONS: Location[] = [
  { id: 'l1', name: 'Marché Jean-Talon',       address: '7070 Henri Julien, Montréal', type: 'Marché',   active: true },
  { id: 'l2', name: 'Épicerie Afro-Antillaise', address: '3456 Boul. Décarie, Montréal', type: 'Épicerie', active: true },
  { id: 'l3', name: 'Marché Atwater',           address: '138 Atwater, Montréal',       type: 'Marché',   active: true },
];

export const SEED_INGREDIENTS: Ingredient[] = [
  {
    id: 'ing-1',
    name: 'Hibiscus (Bissap)',
    image: `${SB}/blog/bissap-culture.jpg`,
    benefits: ['Riche en antioxydants', 'Soutient la circulation', 'Source naturelle de vitamine C'],
    note: 'Importé de Casamance, Sénégal. Base florale de notre Soleil du Sahel.',
    active: true,
  },
  {
    id: 'ing-2',
    name: 'Gingembre bio',
    image: `${SB}/products/feu-gnamakoudji.jpg`,
    benefits: ['Aide la digestion', 'Soutien immunitaire', 'Effet tonique naturel'],
    note: 'Gingembre fraîche biologique. Àme du Feu Gnamakoudji.',
    active: true,
  },
  {
    id: 'ing-3',
    name: 'Moringa',
    image: `${SB}/products/sage-de-la-savane.jpg`,
    benefits: ['92 nutriments essentiels', 'Anti-inflammatoire', 'Source de protéines végétales'],
    note: 'L\u2019arbre miracle du Sahel. Ingredient vedette du Sage de la Savane.',
    active: true,
  },
  {
    id: 'ing-4',
    name: 'Ananas frais',
    image: `${SB}/products/tam-tam-tropical.jpg`,
    benefits: ['Riche en bromélaïne', 'Aide à la digestion', 'Apporte une douceur naturelle'],
    note: 'Pressé à froid dans les 24h de la réception. Coeur du Tam-Tam Tropical.',
    active: true,
  },
  {
    id: 'ing-5',
    name: 'Baobab',
    image: `${SB}/products/fleur-de-baobab.jpg`,
    benefits: ['6x plus de vitamine C que l\u2019orange', 'Riche en calcium', 'Prébiotique naturel'],
    note: 'Pulpe de l\u2019arbre de vie africain. Ingrédient signature de la Fleur de Baobab.',
    active: true,
  },
];

export const SEED_SUBSCRIBERS: Subscriber[] = [
  { id: 's1', email: 'marie@example.com',   date: '2026-01-10', active: true  },
  { id: 's2', email: 'pierre@example.com',  date: '2026-01-22', active: true  },
  { id: 's3', email: 'sophie@example.com',  date: '2026-02-05', active: true  },
  { id: 's4', email: 'jean@example.com',    date: '2026-02-14', active: false },
  { id: 's5', email: 'amelie@example.com',  date: '2026-03-01', active: true  },
];

export const SEED_SETTINGS: Settings = {
  businessName:  "Les Jus Naturels Ben's",
  email:         'info@lesjusnaturelsbens.com',
  phone:         '(514) 839-7420',
  address:       'Marché Jean-Talon, 7070 Henri Julien, Montréal, QC',
  description:   'Jus pressés à froid artisanaux, inspirés de l\u2019Afrique de l\u2019Ouest et du Québec. Sans sucre ajouté, sans conservateurs, pressés à la main dans notre atelier montréalais.',
  facebook:      'https://facebook.com/lesjusnaturelsbens',
  instagram:     'https://instagram.com/lesjusnaturelsbens',
  tiktok:        '',
  website:       'https://lesjusnaturelsbens.com',
  password:      'bens2025',
  heroTitle:     'Offrez-vous un voyage gustatif unique !',
  heroSubtitle:  "En une seule gorgée, savourez le plaisir de nos jus naturels tout en bénéficiant de leurs précieux bienfaits pour votre bien-être.",
  currency:      'CAD',
  taxRate:       14.975,
  deliveryNote:  'Livraison disponible dans la grande région de Montréal. Commande minimum 40\u00a0$.',
};

export const SEED_ACTIVITY: Activity[] = [
  { id: 'a1', action: 'Connexion admin',       detail: 'Première connexion au panneau',              date: '2026-03-01T10:00:00', type: 'auth'     },
  { id: 'a2', action: 'Produit ajouté',   detail: 'Soleil du Sahel ajouté au catalogue',        date: '2026-03-02T14:30:00', type: 'product'  },
  { id: 'a3', action: 'Avis approuvé',    detail: 'Avis de Fatou Diallo approuvé',              date: '2026-03-03T09:15:00', type: 'review'   },
  { id: 'a4', action: 'Article publié',   detail: 'Le Bissap : trésor culturel',                date: '2026-03-04T16:45:00', type: 'blog'     },
  { id: 'a5', action: 'Point de vente ajouté', detail: 'Marché Atwater ajouté',            date: '2026-03-05T11:20:00', type: 'location' },
];

export const SEED_EVENTS: Event[] = [
  {
    id: 'ev1',
    title: 'Atelier Bissap : l\u2019Afrique en bouteille',
    description: 'Venez découvrir les secrets du bissap \u2014 cette fleur d\u2019hibiscus qui voyage du Sénégal jusqu\u2019aux ateliers de Ben\u2019s. Lors de cette expérience immersive de 90 minutes, vous apprendrez l\u2019histoire culturelle du bissap, observerez le processus de pressage à froid en direct et repartirez avec deux bouteilles personnalisées de votre propre mélange.',
    date: '2026-04-19',
    time: '13h00 \u2014 14h30',
    location: 'Atelier Ben\u2019s',
    address: '7070 Henri Julien (Espace Atelier), Montréal',
    type: 'Atelier',
    active: true,
    img: `${SB}/ui/about-atelier.jpg`,
    attendanceEnabled: true,
    maxAttendees: 12,
  },
  {
    id: 'ev2',
    title: 'Marché des Saveurs d\u2019Afrique',
    description: 'Chaque premier samedi du mois, Ben\u2019s s\u2019associe à des artisans africains-québécois pour transformer notre espace en marché festif. Musique live, dégustations de jus frais pressés à la minute, spécialités culinaires et produits artisanaux locaux. Entrée libre.',
    date: '2026-05-02',
    time: '10h00 \u2014 17h00',
    location: 'Esplanade Ben\u2019s',
    address: 'Marché Jean-Talon, Montréal',
    type: 'Marché',
    active: true,
    img: `${SB}/blog/marche-jean-talon.jpg`,
    attendanceEnabled: false,
    maxAttendees: 0,
  },
  {
    id: 'ev3',
    title: 'Festival des Saveurs Africaines',
    description: 'Grande fête culinaire africaine à Montréal. Retrouvez-nous avec toute notre gamme de jus naturels et exotiques pressés à froid. Animations, concerts et rencontres avec les artisans de la communauté.',
    date: '2026-06-21',
    time: '11h00 \u2014 20h00',
    location: 'Parc Lafontaine',
    address: '3933 Av. du Parc-La Fontaine, Montréal',
    type: 'Festival',
    active: true,
    img: `${SB}/ui/hero-banner.jpg`,
    attendanceEnabled: false,
    maxAttendees: 0,
  },
];

export const SEED_STOCK: StockMovement[] = [
  { id: 'st1', productId: 'p1', productName: 'Soleil du Sahel',    type: 'entree', quantity: 48, unit: 'bouteilles', location: 'Entrepôt',          note: 'Production du 2026-03-01', date: '2026-03-01T10:00:00' },
  { id: 'st2', productId: 'p2', productName: 'Rivière Verte',  type: 'entree', quantity: 36, unit: 'bouteilles', location: 'Entrepôt',          note: 'Production du 2026-03-01', date: '2026-03-01T10:30:00' },
  { id: 'st3', productId: 'p1', productName: 'Soleil du Sahel',    type: 'sortie', quantity: 18, unit: 'bouteilles', location: 'Marché Jean-Talon', note: 'Marché samedi 08/03',  date: '2026-03-08T09:00:00' },
  { id: 'st4', productId: 'p2', productName: 'Rivière Verte',  type: 'sortie', quantity: 12, unit: 'bouteilles', location: 'Marché Jean-Talon', note: 'Marché samedi 08/03',  date: '2026-03-08T09:00:00' },
  { id: 'st5', productId: 'p8', productName: 'Feu Gnamakoudji',    type: 'entree', quantity: 60, unit: 'shots',       location: 'Entrepôt',          note: 'Production du 2026-03-05', date: '2026-03-05T14:00:00' },
  { id: 'st6', productId: 'p8', productName: 'Feu Gnamakoudji',    type: 'sortie', quantity: 24, unit: 'shots',       location: 'Épicerie Afro-Antillaise', note: 'Livraison épicerie', date: '2026-03-10T11:00:00' },
];

export const SEED_FINANCE: Transaction[] = [
  { id: 'fi1', type: 'revenu',  amount: 342.50, category: 'Vente marché',   description: 'Marché Jean-Talon \u2014 samedi 08/03',      date: '2026-03-08', location: 'Marché Jean-Talon' },
  { id: 'fi2', type: 'revenu',  amount: 156.00, category: 'Vente épicerie', description: 'Livraison Épicerie Afro-Antillaise',          date: '2026-03-10', location: 'Épicerie Afro-Antillaise' },
  { id: 'fi3', type: 'depense', amount: 89.40,  category: 'Ingrédients',    description: "Fleurs d'hibiscus séchées (2 kg)",        date: '2026-03-02', location: 'Fournisseur Tropicana' },
  { id: 'fi4', type: 'depense', amount: 45.00,  category: 'Emballage',           description: 'Bouteilles 355ml (lot de 100)',                    date: '2026-03-03', location: 'Verreault & Cie' },
  { id: 'fi5', type: 'depense', amount: 15.00,  category: 'Transport',           description: 'Déplacement Marché Jean-Talon',           date: '2026-03-08', location: '' },
  { id: 'fi6', type: 'revenu',  amount: 278.00, category: 'Vente marché',   description: 'Marché Atwater \u2014 dimanche 09/03',         date: '2026-03-09', location: 'Marché Atwater' },
  { id: 'fi7', type: 'depense', amount: 32.00,  category: 'Marketing',           description: 'Impression de flyers A5 (200 ex.)',                 date: '2026-03-05', location: 'Copie Express' },
];

export const SEED_MESSAGES: Message[] = [
  { id: 'm1', name: 'Marie Lavoie',  email: 'marie.lavoie@gmail.com',  message: 'Bonjour, où puis-je acheter vos jus dans le quartier Rosemont\u00a0?',                    read: false, responded: false, date: '2026-03-04T09:30:00' },
  { id: 'm2', name: 'Paul Tremblay', email: 'paul.t@hotmail.com',      message: "J'aimerais savoir si vous faites des collaborations avec des restaurants.",                       read: false, responded: false, date: '2026-03-05T14:15:00' },
  { id: 'm3', name: 'Nadia Benali',  email: 'nadia.b@outlook.com',     message: "Avez-vous le Soleil du Sahel en format 1L\u00a0? Je veux en commander pour toute la famille.",   read: false, responded: false, date: '2026-03-06T08:45:00' },
  { id: 'm4', name: 'Sophie Martin', email: 'sophie.martin@yahoo.com', message: 'Vos jus sont excellents\u00a0! Est-ce que vous livrez à Laval\u00a0?',                       read: true,  responded: true,  date: '2026-02-28T16:20:00' },
];

export const SEED_RECIPES: Recipe[] = [
  {
    id: 'rec1',
    name: 'Smoothie Sahel Sunrise',
    description: 'Un smoothie vibrant inspiré du Soleil du Sahel. Éclatant de couleur, riche en antioxydants \u2014 le début de journée africain par excellence.',
    category: 'Smoothie',
    difficulty: 'Facile',
    prepTime: 8,
    servings: 2,
    products: ['p1', 'p10'],
    ingredients: ["250ml Soleil du Sahel", "150ml Neige Rouge", "1 banane", "100g yaourt de coco", "glaçons"],
    instructions: [
      "Versez les jus dans un mélangeur",
      "Ajoutez la banane coupée en morceaux",
      "Versez le yaourt de coco",
      "Ajoutez une bonne poignée de glaçons",
      "Mélangez jusqu'à obtenir une consistance lisse",
      "Versez dans des verres et servez immédiatement"
    ],
    image: `${SB}/products/soleil-du-sahel.jpg`,
    featured: true,
    published: true,
    tags: ['Tropical', 'Rapide', 'Énergisant'],
  },
  {
    id: 'rec2',
    name: 'Infusion Gnamakoudji Apaisante',
    description: 'Une tisane réconfortante inspirée des soirées ivoiriennes. Elle aide à la digestion et réchauffe l\u2019âme les jours de froid.',
    category: 'Jus',
    difficulty: 'Facile',
    prepTime: 5,
    servings: 1,
    products: ['p8'],
    ingredients: ["60ml Feu Gnamakoudji (shot)", "250ml eau chaude", "1 tranche de citron frais", "1 cuillère de miel cru"],
    instructions: [
      "Versez le shot de Gnamakoudji dans une tasse",
      "Complétez avec 250ml d'eau chaude",
      "Remuez bien",
      "Ajoutez une tranche de citron frais et du miel",
      "Dégustez lentement"
    ],
    image: `${SB}/products/feu-gnamakoudji.jpg`,
    featured: false,
    published: true,
    tags: ['Hivernal', 'Santé', 'Réconfort'],
  },
  {
    id: 'rec3',
    name: 'Cocktail Neige Rouge Festif',
    description: 'Un cocktail éclatant qui rend hommage aux deux cultures de Ben\u2019s. Avec ou sans alcool, il illumine toutes les tables.',
    category: 'Cocktail',
    difficulty: 'Moyen',
    prepTime: 10,
    servings: 2,
    products: ['p10', 'p1'],
    ingredients: ["150ml Neige Rouge", "150ml Soleil du Sahel", "50ml sirop de canne", "60ml rhum blanc (optionnel)", "Glaçons", "Fraises fraîches", "Menthe fraîche"],
    instructions: [
      "Remplissez deux verres de glaçons",
      "Versez 75ml de Neige Rouge dans chaque verre",
      "Ajoutez 75ml de Soleil du Sahel",
      "Versez 30ml de rhum blanc par verre (optionnel)",
      "Complétez avec un trait de sirop de canne",
      "Remuez et garnissez avec des fraises et un brin de menthe"
    ],
    image: `${SB}/products/neige-rouge.jpg`,
    featured: true,
    published: true,
    tags: ['Cocktail', 'Fête', 'Rafraîchissant'],
  },
  {
    id: 'rec4',
    name: 'Bol Énergie Calebasse',
    description: 'Un bol santé inspiré par les saveurs de la Calebasse Dorée \u2014 parfait pour une collation énergisante après l\u2019entraînement.',
    category: 'Desset',
    difficulty: 'Facile',
    prepTime: 10,
    servings: 2,
    products: ['p9', 'p3'],
    ingredients: ["200g purée açaï congelée", "100ml Calebasse Dorée", "50ml Fleur de Baobab", "Granola", "Noix de coco râpée", "Miel cru", "Mangue fraîche"],
    instructions: [
      "Décongelez légèrement la purée d'açaï",
      "Préparez deux bols",
      "Versez une généreuse portion d'açaï dans chaque bol",
      "Arrosez avec la Calebasse Dorée et la Fleur de Baobab",
      "Garnissez de granola et noix de coco râpée",
      "Ajoutez des dés de mangue fraîche",
      "Versez un trait de miel et dégustez immédiatement"
    ],
    image: `${SB}/products/calebasse-doree.jpg`,
    featured: true,
    published: true,
    tags: ['Dessert', 'Sain', 'Énergisant'],
  },
  {
    id: 'rec5',
    name: 'Shot Détox Rivière-Savane',
    description: 'Un duo vert intense pour une détox express. La Rivière Verte et le Sage de la Savane concentrent leurs vertus en un seul verre vivifiant.',
    category: 'Jus',
    difficulty: 'Facile',
    prepTime: 3,
    servings: 1,
    products: ['p2', 'p7'],
    ingredients: ["150ml Rivière Verte", "100ml Sage de la Savane", "Glaçons", "Tranche de citron vert"],
    instructions: [
      "Remplissez un verre de glaçons",
      "Versez la Rivière Verte",
      "Complétez avec le Sage de la Savane",
      "Remuez doucement",
      "Garnissez avec une tranche de citron vert",
      "Servez immédiatement pour une fraîcheur optimale"
    ],
    image: `${SB}/products/riviere-verte.jpg`,
    featured: false,
    published: true,
    tags: ['Détox', 'Rapide', 'Santé'],
  },
  {
    id: 'rec6',
    name: 'Cure Boréale 3 Jours',
    description: 'Une cure de trois jours avec nos jus phares pour revitaliser le corps. Idéal pour les transitions de saison et les remises à zéro.',
    category: 'Jus',
    difficulty: 'Difficile',
    prepTime: 15,
    servings: 3,
    products: ['p5', 'p2', 'p7'],
    ingredients: ["250ml Aurore Boréale (matin)", "250ml Rivière Verte (midi)", "250ml Sage de la Savane (soir)", "Citrons", "Eau filtrée"],
    instructions: [
      "Jour 1\u20133 : Buvez 250ml d'Aurore Boréale le matin à jeun",
      "Midi : Consommez 250ml de Rivière Verte avec votre repas",
      "Soir : Terminez avec 250ml de Sage de la Savane",
      "Entre chaque jus : buvez 500ml d'eau filtrée",
      "Mangez léger : fruits, légumes, céréales",
      "Consultez un professionnel de santé avant de commencer"
    ],
    image: `${SB}/products/aurore-boreale.jpg`,
    featured: false,
    published: true,
    tags: ['Détox', 'Santé', 'Bien-être'],
  },
];
